# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "torch"
        versions: ["<1.7.0"]
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of GitHub workflows
    schedule:
      interval: "weekly"
