[tool.poetry]
name = "dynamic-neural-network-refinement"
version = "0.2.0"
description = "A project for dynamic neural network refinement with state-of-the-art practices."
authors = ["Reece Dixon <qtt@null.net>"]
license = "GNU Affero General Public License v3.0"

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.10.0"
torchvision = "^0.11.1"
pyyaml = "^5.4.1"
wandb = "^0.12.0"
loguru = "^0.5.3"
matplotlib = "^3.4.3"
seaborn = "^0.11.2"
pandas = "^1.3.2"
plotly = "^5.3.1"
ray = { version = "^1.9.1", extras = ["tune"] }
flake8 = "^4.0.1"
black = "^22.3.0"
pytest = "^6.2.5"
great_expectations = "^0.15.15"
dvc = "^2.8.3"
fastapi = "^0.70.0"
uvicorn = "^0.15.0"
json-log-formatter = "^0.3.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
