[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "matplotlib>=3.9.3",
    "numpy>=2.1.3",
    "seaborn>=0.13.2",
    "torch>=2.5.1",
]
