# prometheus/alert.rules.yml

groups:
  - name: app_alerts
    rules:
      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le)) > 1
        for: 2m
        labels:
          severity: "critical"
        annotations:
          summary: "High request latency detected"
          description: "The 95th percentile latency is above 1 second for more than 2 minutes."
