
groups:
  - name: model_monitoring
    rules:
      - alert: HighInferenceLatency
        expr: avg_over_time(inference_latency_seconds[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High inference latency detected

      - alert: LowAccuracy
        expr: model_accuracy < 0.85
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: Model accuracy below threshold

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes > 1e9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
