
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'model_metrics'
    static_configs:
      - targets: ['0.0.0.0:8000']

  - job_name: 'training_metrics'
    static_configs:
      - targets: ['0.0.0.0:8001']
