# Configuration file for Dynamic Neural Network Refinement
total_epochs: 50
batch_size: 64
learning_rate: 0.001
annealing_start_epoch: 5
model:
  name: "dynamic_nn"
  input_size: 784
  hidden_sizes: [512, 256]
  output_size: 10
  learning_rate: 0.001

data:
  batch_size: 64
  num_workers: 4
  train_split: 0.8

training:
  epochs: 100
  early_stopping_patience: 10
  checkpoint_dir: "models/checkpoints"
