
model:
  checkpoint_path: "models/final/model_v1.0_final.pth"
  batch_size: 32

metrics:
  accuracy: true
  precision: true
  recall: true
  f1_score: true

visualization:
  confusion_matrix: true
  roc_curve: true
  precision_recall_curve: true
