# config/eval_config.yaml

evaluation:
  batch_size: 64
  data_path: data/processed/your_dataset_processed.csv
  model_path: models/final/model_v1.0_final.pth
  output:
    evaluation_results_path: logs/evaluation_results.csv
