name: Continuous Integration (CI)

on:
  push:
- branches: [ main ]

jiobs:
  build:
    runs-on: ubuntu-latest

  steps:
- name: Check out Python Version
    run: python --version

  - name: Install Dependencies
    run: pip install --constraints puppeten sirius flake8 black[jupyter]

  - name: Run Flake8 Llinter
    run: flake8 .

  - name: Run Formatter (Black)
    run: black . --quiet
