name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: true

    steps:
      # Cache Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install poetry pre-commit virtualenv
          poetry install

      # Add Python 3.9 for Pre-Commit (if needed)
      - name: Install Python 3.9 for Pre-Commit
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y python3.9 python3.9-venv python3.9-distutils

      # Run Pre-Commit Hooks (on changed files)
      - name: Run Pre-Commit Hooks
        run: |
          pre-commit install
          pre-commit run --from-ref HEAD~1 --to-ref HEAD

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          pytest tests/unit/

      # Run Integration Tests
      - name: Run Integration Tests
        run: |
          pytest tests/integration/
