# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
          pip install pytest flake8 black bandit

      - name: Configure DVC remote
        run: |
          dvc remote add -d myremote ${{ secrets.DVC_REMOTE_URL }}
          dvc pull

      - name: Lint with flake8
        run: |
          flake8 src/ scripts/ tests/

      - name: Format code with black
        run: |
          black --check src/ scripts/ tests/

      - name: Run Bandit security scan
        run: |
          bandit -r src/ scripts/ tests/

      - name: Run unit tests
        run: |
          pytest tests/unit/

      - name: Run integration tests
        run: |
          python -m unittest tests/test_integration.py

      - name: Run end-to-end tests
        run: |
          python -m unittest tests/test_e2e.py

      - name: Validate data
        run: |
          python scripts/validate_data.py --suite your_suite_name --data_path data/processed/your_dataset_processed.csv

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
