name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses:
          actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools pre-commit
          pip install poetry
          poetry install

      - name: Install Python 3.9 for Pre-Commit (if required)
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.9 python3.9-venv python3.9-distutils

      - name: Run Pre-Commit Hooks
        run: |
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure

      - name: Code Formatting with Black
        run: |
          black . --check

      - name: Code Linting with Flake8
        run: |
          flake8 .

      - name: Security Check with Bandit
        run: |
          bandit -r src/

      - name: Run Unit Tests
        run: |
          pytest tests/unit/

      - name: Run Integration Tests
        run: |
          pytest tests/integration/
