# .github/workflows/training.yml

name: Training

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run training
        run: |
          python scripts/train.py --config config/train_config.yaml

      - name: Upload training logs
        uses: actions/upload-artifact@v2
        with:
          name: training-logs
          path: logs/train.json.log
